ESPIDF ?= $(HOME)/esp/esp-idf
CROSS_COMPILE ?= $(HOME)/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-
PYTHON=python3

BOARD ?= LILYGO_T_WATCH_2020_V1
PORT ?= /dev/ttyUSB0
FLASH_MODE ?= dio
FLASH_SIZE ?= 16MB
USER_C_MODULES=boards/LILYGO_T_WATCH_2020_V1/c_drivers

include Makefile.mk
